/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Go Template API - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'health.check': ['GET', '/api/v1/health'],
  'notepad.list': ['GET', '/api/v1/notepads'],
  'notepad.create': ['POST', '/api/v1/notepads'],
  'notepad.delete': ['DELETE', '/api/v1/notepads/{id}'],
  'notepad.get': ['GET', '/api/v1/notepads/{id}'],
  'notepad.update': ['PATCH', '/api/v1/notepads/{id}'],
  'notepad.move': ['POST', '/api/v1/notepads/{id}/move'],
  'project.list': ['GET', '/api/v1/projects'],
  'project.create': ['POST', '/api/v1/projects'],
  'project.delete': ['DELETE', '/api/v1/projects/{id}'],
  'project.getById': ['GET', '/api/v1/projects/{id}'],
  'branch.list': ['GET', '/api/v1/projects/{projectId}/branches'],
  'branch.create': ['POST', '/api/v1/projects/{projectId}/branches'],
  'branch.delete': ['DELETE', '/api/v1/projects/{projectId}/branches/{branchName}'],
  'worktree.refreshAllByProject': ['POST', '/api/v1/projects/{projectId}/refresh-all-worktrees'],
  'worktree.syncByProject': ['POST', '/api/v1/projects/{projectId}/sync-worktrees'],
  'task.list': ['GET', '/api/v1/projects/{projectId}/tasks'],
  'task.create': ['POST', '/api/v1/projects/{projectId}/tasks'],
  'terminalSession.list': ['GET', '/api/v1/projects/{projectId}/terminals'],
  'terminalSession.close': ['DELETE', '/api/v1/projects/{projectId}/terminals/{sessionId}'],
  'terminalSession.rename': ['PATCH', '/api/v1/projects/{projectId}/terminals/{sessionId}'],
  'worktree.listByProject': ['GET', '/api/v1/projects/{projectId}/worktrees'],
  'worktree.create': ['POST', '/api/v1/projects/{projectId}/worktrees'],
  'terminalSession.create': ['POST', '/api/v1/projects/{projectId}/worktrees/{worktreeId}/terminals'],
  'ptyTest.sessionCreate': ['POST', '/api/v1/pty-test/sessions'],
  'ptyTest.sessionClose': ['DELETE', '/api/v1/pty-test/sessions/{sessionId}'],
  'system.openExplorer': ['POST', '/api/v1/system/open-explorer'],
  'system.openTerminal': ['POST', '/api/v1/system/open-terminal'],
  'taskComment.delete': ['DELETE', '/api/v1/task-comments/{id}'],
  'task.delete': ['DELETE', '/api/v1/tasks/{id}'],
  'task.getById': ['GET', '/api/v1/tasks/{id}'],
  'task.update': ['PATCH', '/api/v1/tasks/{id}'],
  'task.bindWorktree': ['POST', '/api/v1/tasks/{id}/bind-worktree'],
  'taskComment.list': ['GET', '/api/v1/tasks/{id}/comments'],
  'taskComment.create': ['POST', '/api/v1/tasks/{id}/comments'],
  'task.move': ['POST', '/api/v1/tasks/{id}/move'],
  'upload.clipboardImage': ['POST', '/api/v1/upload/clipboard-image'],
  'worktree.delete': ['DELETE', '/api/v1/worktrees/{id}'],
  'worktree.commit': ['POST', '/api/v1/worktrees/{id}/commit'],
  'branch.merge': ['POST', '/api/v1/worktrees/{id}/merge'],
  'worktree.refreshStatus': ['POST', '/api/v1/worktrees/{id}/refresh-status']
};
