/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Code Kanban - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'health.check': ['GET', '/api/v1/health'],
  'notepad.list': ['GET', '/api/v1/notepads'],
  'notepad.create': ['POST', '/api/v1/notepads/create'],
  'notepad.get': ['GET', '/api/v1/notepads/{id}'],
  'notepad.delete': ['POST', '/api/v1/notepads/{id}/delete'],
  'notepad.move': ['POST', '/api/v1/notepads/{id}/move'],
  'notepad.update': ['POST', '/api/v1/notepads/{id}/update'],
  'project.list': ['GET', '/api/v1/projects'],
  'project.create': ['POST', '/api/v1/projects/create'],
  'project.getById': ['GET', '/api/v1/projects/{id}'],
  'project.delete': ['POST', '/api/v1/projects/{id}/delete'],
  'project.updatePriority': ['POST', '/api/v1/projects/{id}/priority'],
  'project.update': ['POST', '/api/v1/projects/{id}/update'],
  'project.gitCapabilities': ['GET', '/api/v1/projects/{projectId}/git-capabilities'],
  'branch.list': ['GET', '/api/v1/projects/{projectId}/branches'],
  'branch.create': ['POST', '/api/v1/projects/{projectId}/branches/create'],
  'branch.delete': ['POST', '/api/v1/projects/{projectId}/branches/{branchName}'],
  'worktree.refreshAllByProject': ['POST', '/api/v1/projects/{projectId}/refresh-all-worktrees'],
  'worktree.syncByProject': ['POST', '/api/v1/projects/{projectId}/sync-worktrees'],
  'terminalSession.list': ['GET', '/api/v1/projects/{projectId}/terminals'],
  'terminalSession.close': ['POST', '/api/v1/projects/{projectId}/terminals/{sessionId}/close'],
  'terminalSession.rename': ['POST', '/api/v1/projects/{projectId}/terminals/{sessionId}/rename'],
  'worktree.listByProject': ['GET', '/api/v1/projects/{projectId}/worktrees'],
  'worktree.create': ['POST', '/api/v1/projects/{projectId}/worktrees/create'],
  'worktree.refreshCommitInfo': ['POST', '/api/v1/projects/{projectId}/worktrees/refresh-commits'],
  'terminalSession.create': [
    'POST',
    '/api/v1/projects/{projectId}/worktrees/{worktreeId}/terminals',
  ],
  'system.checkUpdate': ['GET', '/api/v1/system/check-update'],
  'system.developerConfigGet': ['GET', '/api/v1/system/developer-config'],
  'system.developerConfigUpdate': ['POST', '/api/v1/system/developer-config/update'],
  'system.gitSettingsGet': ['GET', '/api/v1/system/git-settings'],
  'system.gitSettingsUpdate': ['POST', '/api/v1/system/git-settings/update'],
  'system.openEditor': ['POST', '/api/v1/system/open-editor'],
  'system.openExplorer': ['POST', '/api/v1/system/open-explorer'],
  'system.openTerminal': ['POST', '/api/v1/system/open-terminal'],
  'system.version': ['GET', '/api/v1/system/version'],
  'terminalSession.terminalCounts': ['GET', '/api/v1/terminals/counts'],
  'terminalSession.captureChunk': ['GET', '/api/v1/terminals/{sessionId}/capture'],
  'terminalSession.debug': ['GET', '/api/v1/terminals/{sessionId}/debug'],
  'upload.clipboardImage': ['POST', '/api/v1/upload/clipboard-image'],
  'worktree.delete': ['POST', '/api/v1/worktrees/{id}'],
  'worktree.commit': ['POST', '/api/v1/worktrees/{id}/commit'],
  'branch.merge': ['POST', '/api/v1/worktrees/{id}/merge'],
  'worktree.refreshStatus': ['POST', '/api/v1/worktrees/{id}/refresh-status'],
  // AI Session routes
  'aiSession.listByProject': ['GET', '/api/v1/projects/{id}/ai-sessions'],
  'aiSession.getConversation': ['GET', '/api/v1/ai-sessions/{id}/conversation'],
};
