import type { ThemeSettings } from '@/stores/settings';

export interface ThemePreset {
  id: string;
  name: string;
  nameEn: string;
  isDark: boolean;
  colors: ThemeSettings;
  terminalThemeId: string;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'light',
    name: '亮色',
    nameEn: 'Light',
    isDark: false,
    terminalThemeId: 'light',
    colors: {
      primaryColor: '#3B69A9',
      bodyColor: '#F7F8FA',
      surfaceColor: '#FFFFFF',
      textColor: '#333333',
      terminalBg: '#0c0c0c',
      terminalFg: '#1E1E1E',
      terminalTabBg: '#F1F1F1',
      terminalTabActiveBg: '#FFFFFF',
      terminalHeaderBorder: false,
      // 完成提醒 - 亮色主题用更深的绿色
      terminalTabCompletionBg: 'rgba(16, 185, 129, 0.25)',
      terminalTabCompletionBorder: 'rgba(16, 185, 129, 0.5)',
      // 审批提醒 - 亮色主题用更深的橙色
      terminalTabApprovalBg: 'rgba(247, 144, 9, 0.25)',
      terminalTabApprovalBorder: 'rgba(247, 144, 9, 0.5)',
      // 浮动按钮 - 黑底白字
      terminalFloatingButtonBg: '#1a1a1a',
      terminalFloatingButtonFg: '#ffffff',
      // 空终端引导文字 - 白色
      terminalEmptyGuideFg: '#ffffff',
      // 看板背景和卡片背景
      kanbanBoardBg: '#f5f5f5',
      kanbanCardBg: '#ffffff',
      kanbanBorderEnabled: false,
    },
  },
  {
    id: 'dark',
    name: '暗色',
    nameEn: 'Dark',
    isDark: true,
    terminalThemeId: 'nord',
    colors: {
      primaryColor: '#007ACC',
      bodyColor: '#1E1E1E',
      surfaceColor: '#252526',
      textColor: '#D4D4D4',
      terminalBg: '#2E3440',
      terminalFg: '#D8DEE9',
      terminalTabBg: '#252526',
      terminalTabActiveBg: '#2E3440',
      terminalHeaderBorder: false,
      terminalTabCompletionBg: 'rgba(163, 190, 140, 0.25)',
      terminalTabCompletionBorder: 'rgba(163, 190, 140, 0.5)',
      terminalTabApprovalBg: 'rgba(235, 203, 139, 0.25)',
      terminalTabApprovalBorder: 'rgba(235, 203, 139, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#D8DEE9',
      kanbanBoardBg: '#1E1E1E',
      kanbanCardBg: '#2a2a2b',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'dim',
    name: '柔和暗色',
    nameEn: 'Dim',
    isDark: true,
    terminalThemeId: 'github-dark',
    colors: {
      primaryColor: '#539BF5',
      bodyColor: '#22272E',
      surfaceColor: '#2D333B',
      textColor: '#BDC9D4',
      terminalBg: '#0D1117',
      terminalFg: '#E6EDF3',
      terminalTabBg: '#2D333B',
      terminalTabActiveBg: '#0D1117',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(63, 185, 80, 0.25)',
      terminalTabCompletionBorder: 'rgba(63, 185, 80, 0.5)',
      terminalTabApprovalBg: 'rgba(210, 153, 34, 0.25)',
      terminalTabApprovalBorder: 'rgba(210, 153, 34, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#E6EDF3',
      kanbanBoardBg: '#22272E',
      kanbanCardBg: '#373e47',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'warm',
    name: '暖色',
    nameEn: 'Warm',
    isDark: false,
    terminalThemeId: 'warm-light',
    colors: {
      primaryColor: '#D97706',
      bodyColor: '#FEF3C7',
      surfaceColor: '#FFFBEB',
      textColor: '#78350F',
      terminalBg: '#FFF7ED',
      terminalFg: '#7C2D12',
      terminalTabBg: '#FFFBEB',
      terminalTabActiveBg: '#FFF7ED',
      terminalHeaderBorder: false,
      terminalTabCompletionBg: 'rgba(5, 150, 105, 0.25)',
      terminalTabCompletionBorder: 'rgba(5, 150, 105, 0.5)',
      terminalTabApprovalBg: 'rgba(217, 119, 6, 0.25)',
      terminalTabApprovalBorder: 'rgba(217, 119, 6, 0.5)',
      terminalFloatingButtonBg: '#1a1a1a',
      terminalFloatingButtonFg: '#ffffff',
      terminalEmptyGuideFg: '#7C2D12',
      kanbanBoardBg: '#FEF3C7',
      kanbanCardBg: '#FFFBEB',
      kanbanBorderEnabled: false,
    },
  },
  {
    id: 'material-dark',
    name: 'Material 暗色',
    nameEn: 'Material Dark',
    isDark: true,
    terminalThemeId: 'material-dark',
    colors: {
      primaryColor: '#BB86FC',
      bodyColor: '#121212',
      surfaceColor: '#1F1B24',
      textColor: '#E6E1E5',
      terminalBg: '#0F0F0F',
      terminalFg: '#E6E1E5',
      terminalTabBg: '#1F1B24',
      terminalTabActiveBg: '#0F0F0F',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(3, 218, 198, 0.25)',
      terminalTabCompletionBorder: 'rgba(3, 218, 198, 0.5)',
      terminalTabApprovalBg: 'rgba(255, 171, 64, 0.25)',
      terminalTabApprovalBorder: 'rgba(255, 171, 64, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#E6E1E5',
      kanbanBoardBg: '#121212',
      kanbanCardBg: '#2d2833',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'xcode-dark',
    name: 'Xcode 暗色',
    nameEn: 'Xcode Dark',
    isDark: true,
    terminalThemeId: 'xcode-dark',
    colors: {
      primaryColor: '#0A84FF',
      bodyColor: '#1E1F22',
      surfaceColor: '#2C2D31',
      textColor: '#F5F5F7',
      terminalBg: '#1A1B1E',
      terminalFg: '#F5F5F7',
      terminalTabBg: '#2C2D31',
      terminalTabActiveBg: '#1A1B1E',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(48, 209, 88, 0.25)',
      terminalTabCompletionBorder: 'rgba(48, 209, 88, 0.5)',
      terminalTabApprovalBg: 'rgba(255, 214, 10, 0.25)',
      terminalTabApprovalBorder: 'rgba(255, 214, 10, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#F5F5F7',
      kanbanBoardBg: '#1E1F22',
      kanbanCardBg: '#36373b',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized 亮色',
    nameEn: 'Solarized Light',
    isDark: false,
    terminalThemeId: 'solarized-light',
    colors: {
      primaryColor: '#268BD2',
      bodyColor: '#FDF6E3',
      surfaceColor: '#F5EFD5',
      textColor: '#073642',
      terminalBg: '#FDF6E3',
      terminalFg: '#586E75',
      terminalTabBg: '#F5EFD5',
      terminalTabActiveBg: '#FDF6E3',
      terminalHeaderBorder: false,
      terminalTabCompletionBg: 'rgba(133, 153, 0, 0.25)',
      terminalTabCompletionBorder: 'rgba(133, 153, 0, 0.5)',
      terminalTabApprovalBg: 'rgba(181, 137, 0, 0.25)',
      terminalTabApprovalBorder: 'rgba(181, 137, 0, 0.5)',
      terminalFloatingButtonBg: '#1a1a1a',
      terminalFloatingButtonFg: '#ffffff',
      terminalEmptyGuideFg: '#586E75',
      kanbanBoardBg: '#FDF6E3',
      kanbanCardBg: '#F5EFD5',
      kanbanBorderEnabled: false,
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized 暗色',
    nameEn: 'Solarized Dark',
    isDark: true,
    terminalThemeId: 'solarized-dark',
    colors: {
      primaryColor: '#859900',
      bodyColor: '#002B36',
      surfaceColor: '#073642',
      textColor: '#EEE8D5',
      terminalBg: '#002B36',
      terminalFg: '#93A1A1',
      terminalTabBg: '#073642',
      terminalTabActiveBg: '#002B36',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(133, 153, 0, 0.25)',
      terminalTabCompletionBorder: 'rgba(133, 153, 0, 0.5)',
      terminalTabApprovalBg: 'rgba(181, 137, 0, 0.25)',
      terminalTabApprovalBorder: 'rgba(181, 137, 0, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#93A1A1',
      kanbanBoardBg: '#002B36',
      kanbanCardBg: '#094652',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    nameEn: 'Nord',
    isDark: true,
    terminalThemeId: 'nord',
    colors: {
      primaryColor: '#88C0D0',
      bodyColor: '#2E3440',
      surfaceColor: '#3B4252',
      textColor: '#ECEFF4',
      terminalBg: '#2E3440',
      terminalFg: '#D8DEE9',
      terminalTabBg: '#3B4252',
      terminalTabActiveBg: '#2E3440',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(163, 190, 140, 0.25)',
      terminalTabCompletionBorder: 'rgba(163, 190, 140, 0.5)',
      terminalTabApprovalBg: 'rgba(235, 203, 139, 0.25)',
      terminalTabApprovalBorder: 'rgba(235, 203, 139, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#D8DEE9',
      kanbanBoardBg: '#2E3440',
      kanbanCardBg: '#434c5e',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    nameEn: 'Dracula',
    isDark: true,
    terminalThemeId: 'dracula',
    colors: {
      primaryColor: '#BD93F9',
      bodyColor: '#282A36',
      surfaceColor: '#343746',
      textColor: '#F8F8F2',
      terminalBg: '#282A36',
      terminalFg: '#F8F8F2',
      terminalTabBg: '#343746',
      terminalTabActiveBg: '#282A36',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(80, 250, 123, 0.25)',
      terminalTabCompletionBorder: 'rgba(80, 250, 123, 0.5)',
      terminalTabApprovalBg: 'rgba(241, 250, 140, 0.25)',
      terminalTabApprovalBorder: 'rgba(241, 250, 140, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#F8F8F2',
      kanbanBoardBg: '#282A36',
      kanbanCardBg: '#414558',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    nameEn: 'One Dark',
    isDark: true,
    terminalThemeId: 'one-dark',
    colors: {
      primaryColor: '#61AFEF',
      bodyColor: '#21252B',
      surfaceColor: '#282C34',
      textColor: '#ABB2BF',
      terminalBg: '#1E2127',
      terminalFg: '#ABB2BF',
      terminalTabBg: '#282C34',
      terminalTabActiveBg: '#1E2127',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(152, 195, 121, 0.25)',
      terminalTabCompletionBorder: 'rgba(152, 195, 121, 0.5)',
      terminalTabApprovalBg: 'rgba(209, 154, 102, 0.25)',
      terminalTabApprovalBorder: 'rgba(209, 154, 102, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#ABB2BF',
      kanbanBoardBg: '#21252B',
      kanbanCardBg: '#31353f',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    nameEn: 'Tokyo Night',
    isDark: true,
    terminalThemeId: 'tokyo-night',
    colors: {
      primaryColor: '#7AA2F7',
      bodyColor: '#1A1B26',
      surfaceColor: '#24283B',
      textColor: '#C0CAF5',
      terminalBg: '#1A1B26',
      terminalFg: '#A9B1D6',
      terminalTabBg: '#24283B',
      terminalTabActiveBg: '#1A1B26',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(158, 206, 106, 0.25)',
      terminalTabCompletionBorder: 'rgba(158, 206, 106, 0.5)',
      terminalTabApprovalBg: 'rgba(224, 175, 104, 0.25)',
      terminalTabApprovalBorder: 'rgba(224, 175, 104, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#A9B1D6',
      kanbanBoardBg: '#1A1B26',
      kanbanCardBg: '#2f3241',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'github-dark',
    name: 'GitHub 暗色',
    nameEn: 'GitHub Dark',
    isDark: true,
    terminalThemeId: 'github-dark',
    colors: {
      primaryColor: '#58A6FF',
      bodyColor: '#0D1117',
      surfaceColor: '#161B22',
      textColor: '#E6EDF3',
      terminalBg: '#0D1117',
      terminalFg: '#E6EDF3',
      terminalTabBg: '#161B22',
      terminalTabActiveBg: '#0D1117',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(63, 185, 80, 0.25)',
      terminalTabCompletionBorder: 'rgba(63, 185, 80, 0.5)',
      terminalTabApprovalBg: 'rgba(210, 153, 34, 0.25)',
      terminalTabApprovalBorder: 'rgba(210, 153, 34, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#E6EDF3',
      kanbanBoardBg: '#0D1117',
      kanbanCardBg: '#1e2329',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    nameEn: 'Monokai',
    isDark: true,
    terminalThemeId: 'monokai',
    colors: {
      primaryColor: '#A6E22E',
      bodyColor: '#272822',
      surfaceColor: '#3E3D32',
      textColor: '#F8F8F2',
      terminalBg: '#272822',
      terminalFg: '#F8F8F2',
      terminalTabBg: '#3E3D32',
      terminalTabActiveBg: '#272822',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(166, 226, 46, 0.25)',
      terminalTabCompletionBorder: 'rgba(166, 226, 46, 0.5)',
      terminalTabApprovalBg: 'rgba(244, 191, 117, 0.25)',
      terminalTabApprovalBorder: 'rgba(244, 191, 117, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#F8F8F2',
      kanbanBoardBg: '#272822',
      kanbanCardBg: '#4a4a3d',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox 暗色',
    nameEn: 'Gruvbox Dark',
    isDark: true,
    terminalThemeId: 'gruvbox-dark',
    colors: {
      primaryColor: '#FABD2F',
      bodyColor: '#282828',
      surfaceColor: '#3C3836',
      textColor: '#EBDBB2',
      terminalBg: '#282828',
      terminalFg: '#EBDBB2',
      terminalTabBg: '#3C3836',
      terminalTabActiveBg: '#282828',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(152, 151, 26, 0.25)',
      terminalTabCompletionBorder: 'rgba(152, 151, 26, 0.5)',
      terminalTabApprovalBg: 'rgba(215, 153, 33, 0.25)',
      terminalTabApprovalBorder: 'rgba(215, 153, 33, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#EBDBB2',
      kanbanBoardBg: '#282828',
      kanbanCardBg: '#484442',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin',
    nameEn: 'Catppuccin Mocha',
    isDark: true,
    terminalThemeId: 'catppuccin',
    colors: {
      primaryColor: '#CBA6F7',
      bodyColor: '#1E1E2E',
      surfaceColor: '#313244',
      textColor: '#CDD6F4',
      terminalBg: '#1E1E2E',
      terminalFg: '#CDD6F4',
      terminalTabBg: '#313244',
      terminalTabActiveBg: '#1E1E2E',
      terminalHeaderBorder: 'transparent',
      terminalTabCompletionBg: 'rgba(166, 227, 161, 0.25)',
      terminalTabCompletionBorder: 'rgba(166, 227, 161, 0.5)',
      terminalTabApprovalBg: 'rgba(249, 226, 175, 0.25)',
      terminalTabApprovalBorder: 'rgba(249, 226, 175, 0.5)',
      terminalFloatingButtonBg: '#ffffff',
      terminalFloatingButtonFg: '#1a1a1a',
      terminalEmptyGuideFg: '#CDD6F4',
      kanbanBoardBg: '#1E1E2E',
      kanbanCardBg: '#3f3f54',
      kanbanBorderEnabled: true,
    },
  },
  {
    id: 'github-light',
    name: 'GitHub 亮色',
    nameEn: 'GitHub Light',
    isDark: false,
    terminalThemeId: 'github-light',
    colors: {
      primaryColor: '#0969DA',
      bodyColor: '#F6F8FA',
      surfaceColor: '#FFFFFF',
      textColor: '#1F2328',
      terminalBg: '#F6F8FA',
      terminalFg: '#1F2328',
      terminalTabBg: '#FFFFFF',
      terminalTabActiveBg: '#F6F8FA',
      terminalHeaderBorder: false,
      terminalTabCompletionBg: 'rgba(17, 99, 41, 0.25)',
      terminalTabCompletionBorder: 'rgba(17, 99, 41, 0.5)',
      terminalTabApprovalBg: 'rgba(77, 45, 0, 0.25)',
      terminalTabApprovalBorder: 'rgba(77, 45, 0, 0.5)',
      terminalFloatingButtonBg: '#1a1a1a',
      terminalFloatingButtonFg: '#ffffff',
      terminalEmptyGuideFg: '#1F2328',
      kanbanBoardBg: '#F6F8FA',
      kanbanCardBg: '#FFFFFF',
      kanbanBorderEnabled: false,
    },
  },
  {
    id: 'gruvbox-light',
    name: 'Gruvbox 亮色',
    nameEn: 'Gruvbox Light',
    isDark: false,
    terminalThemeId: 'gruvbox-light',
    colors: {
      primaryColor: '#B57614',
      bodyColor: '#FBF1C7',
      surfaceColor: '#F2E5BC',
      textColor: '#3C3836',
      terminalBg: '#FBF1C7',
      terminalFg: '#3C3836',
      terminalTabBg: '#F2E5BC',
      terminalTabActiveBg: '#FBF1C7',
      terminalHeaderBorder: false,
      terminalTabCompletionBg: 'rgba(152, 151, 26, 0.25)',
      terminalTabCompletionBorder: 'rgba(152, 151, 26, 0.5)',
      terminalTabApprovalBg: 'rgba(215, 153, 33, 0.25)',
      terminalTabApprovalBorder: 'rgba(215, 153, 33, 0.5)',
      terminalFloatingButtonBg: '#1a1a1a',
      terminalFloatingButtonFg: '#ffffff',
      terminalEmptyGuideFg: '#3C3836',
      kanbanBoardBg: '#FBF1C7',
      kanbanCardBg: '#F2E5BC',
      kanbanBorderEnabled: false,
    },
  },
];

export const DEFAULT_PRESET_ID = 'light';

export function getPresetById(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find(preset => preset.id === id);
}

export function getDefaultPreset(): ThemePreset {
  return getPresetById(DEFAULT_PRESET_ID) || THEME_PRESETS[0];
}
