<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
    role="img"
    id="goal"
    data-name="Line Color"
    class="icon line-color"
    viewBox="0 0 24 24"
    width="24"
    height="24"
    fill="none"
  >
    <path
      id="secondary"
      d="M15,9l-2.5,2.5M15,6V9h3l3-3H18V3Z"
      stroke="currentColor"
      stroke-width="1.5"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
    <path
      id="primary"
      d="M12.33,3H12a9,9,0,1,0,9,9c0-.11,0-.22,0-.33"
      stroke="currentColor"
      stroke-width="1.5"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
    <path
      id="primary-2"
      data-name="primary"
      d="M16.9,13A5,5,0,1,1,11,7.1"
      stroke="currentColor"
      stroke-width="1.5"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
  </svg>
</template>
